services:
  postgres:
    image: postgres:16
    container_name: memory-postgres

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: chatbot

    ports:
      - "5442:5432"